

var MongoClient = require('mongodb').MongoClient;
var url = "mongodb://csc309f:csc309fall@ds117316.mlab.com:17316/csc309db";
var express = require('express');

var app = express();

app.disable('x-powered-by'); //blocks header from containing info about our server, for security reasons

var handlebars = require('express-handlebars').create({defaultLayout:'main'});
app.engine('handlebars', handlebars.engine);
app.set('view engine', 'handlebars');

app.use(require('body-parser').urlencoded({extended: true}));

var formidable = require('formidable');

//credentials, for cookies and sessions, to help with security
var credentials = require('./credentials.js');
app.use(require('cookie-parser')(credentials.cookieSecret));

app.set('port', process.env.PORT || 3000); //web app runs on port 3000

app.use(express.static(__dirname + '/public'));
//localhost3000/
app.get('/', function(req, res){
  res.render('home'); //references home handlebar
});

app.get('/junk', function(req, res, next){
  console.log('Tried to access /junk');
  throw new Error('/junk doesn\'t exist');
});

app.use(function(err, req, res, next){
  console.log('Error : ' + err.message);
  next();
});

app.get('/petspotlight', function(req, res){
  res.render('about');
});

//csrf token generated by cookie and form data, verified when posting
app.get('/profile', function(req, res){
  res.render('profile', { csrf: 'CSRF token here'});
});

app.get('/thankyou', function(req, res){
  res.render('thankyou');
});

app.post('/process', function(req,res){
  console.log('Form : ' + req.query.form);
  console.log('CSRF token : ' + req.body._csrf);
  console.log('Email : ' + req.body.email);
  console.log('Question : ' + req.body.ques);


  MongoClient.connect(url, function(err,res){
        if(err) console.log(err)
            console.log("Database connected");
            db = res
            //add documents
            var data = {user: req.body.email, password: req.body.ques}

            // Add functions here
            // db.collection("suke1_COLLECTION").insertOne(data, function(err,res){
            //     if (err) {
            //         console.log(err);
            //     }
            //     else{
            //         console.log("1 document inserted");
            //         db.close();
            //     }
            // });

            //TASK 1 inserting an array (use insert not insertone)
            db.collection("suke1test_COLLECTION").insertOne(data, function(err,res){
                if (err) {
                    console.log(err);
                }
                else{
                    console.log("user inserted");
                    db.close();
                }
            });

            console.log("db find")
            //console.log(db.collection("csc309db.suke1test_COLLECTION").find({}));
           db.collection("suke1test_COLLECTION").find({}).toArray(function (err, docs) {
        if (err) {
            console.log('Error');
            console.log(err);
            res.end();
        }
        else {
            console.log('Success');
            console.log(docs);
        }
    });
            //console.log(db.collection("suke1purchases_COLLECTION").find({name: true, address: true}));
            //.log(db.collection("suke1purchases_COLLECTION").find({}, {_id: false, name: true, address: true, ph_num: false, amount: false}) );
            //console.log(db.collection("suke1purchases_COLLECTION").find({}, {_id:false, name: true, address: true}) );
    });


  res.redirect(303, '/thankyou');
});

app.get('/file-upload', function(req, res){
  var now = new Date();
  res.render('file-upload',{
    year: now.getFullYear(),
    month: now.getMonth() });
  });

app.post('/file-upload/:year/:month',
  function(req, res){
    var form = new formidable.IncomingForm(); //parsing file
    form.parse(req, function(err, fields, file){
      if(err)
        return res.redirect(303, '/error');
      console.log('Received File');

      console.log(file);
      res.redirect( 303, '/thankyou');
  });
});

app.get('/cookie', function(req, res){
  res.cookie('username', 'Derek Banas', {expire: new Date() + 9999}).send('username has the value of Derek Banas');
});

app.get('/listcookies', function(req, res){
  console.log("Cookies : ", req.cookies);
  res.send('Look in the console for cookies');
});

app.get('/deletecookie', function(req, res){
  res.clearCookie('username');
  res.send('username Cookie Deleted');
});

// var session = require('express-session');

// var parseurl = require('parseurl');

// app.use(session({
//   resave: false,
//   saveUninitialized: true,
//   secret: credentials.cookieSecret,
// }));

// app.use(function(req, res, next){
//   var views = req.session.views;

//   if(!views){
//     views = req.session.views = {};
//   }

//   var pathname = parseurl(req).pathname;

//   views[pathname] = (views[pathname] || 0) + 1;

//   next();

// });

// app.get('/viewcount', function(req, res, next){
//   res.send('You viewed this page ' + req.session.views['/viewcount'] + ' times');
// });

// var fs = require("fs");

// app.get('/readfile', function(req, res, next){
//   fs.readFile('./public/randomfile.txt', function(err, data){
//       if(err){
//         return console.error(err);
//       }
//       res.send("the File : " + data.toString());
//   });
// });

// app.get('/writefile', function(req, res, next){
//   fs.writeFile('./public/randomfile2.txt',
//     'More random text', function(err){
//       if(err){
//         return console.error(err);
//       }
//     });

//   fs.readFile('./public/randomfile2.txt', function(err, data){
//     if(err){
//       return console.error(err);
//     }
//     res.send("The File " + data.toString());
//   });

// });

app.use(function(req, res){
  res.type('text/html');
  res.status(404);
  res.render('404');
});

app.use(function(err, req, res, next){
  console.error(err.stack);
  res.status(500);
  res.render('500');
});

//app listens on port 3000
app.listen(app.get('port'), function(){
  console.log('Express started on http://localhost:' + app.get('port') + ' press Ctrl-C to terminate');
});


//installed body parser
//instaled formidable to parse images